version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-name: io.kokuwa.maven:maven-parent
      - dependency-name: org.keycloak:keycloak-quarkus-server
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
