version: '3'

services:
  keycloak:
      image: quay.io/keycloak/keycloak:21.0.2
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KC_HTTP_RELATIVE_PATH: /auth
        KC_HEALTH_ENABLED: true
        KC_METRICS_ENABLED: true
      ports:
        - 8080:8080
      volumes: 
        - ./target/keycloak-event-metrics-0.2.1-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-event-metrics.jar
      command: [ "start-dev" ] 
