when:
  instance: ci.kokuwa.io
  event: [manual, pull_request]
  path: [.woodpecker/verify.yaml, pom.xml, src/**]

services:
  - name: dockerd
    image: kokuwaio/dockerd:28.2.2-rootless
    privileged: true
    ports: [2375, 8080]

steps:

  test:
    image: maven:3.9.10-eclipse-temurin-17
    commands: mvn verify --settings=.woodpecker/maven/settings.xml

  image:
    image: kokuwaio/buildctl:v0.23.2
    settings:
      platform: [linux/amd64, linux/arm64]
    when:
      instance: ci.kokuwa.io
