name: Verify

on:
  - pull_request
  - push:
      branches: [main]

env:
  MAVEN_ARGS: --batch-mode --color=always --no-transfer-progress

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-java@main
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - run: mvn verify

  versions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - 22.0.5
          - 23.0.7
          - 24.0.5
          - 25.0.6
          - 26.2.5
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-java@main
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - run: mvn verify -Dversion.org.keycloak.test=${{ matrix.version }}
