name: CI

on:
  push:
    branches: [main]
  pull_request: {}

jobs:

  yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ibiqlik/action-yamllint@v3
        with:
          format: colored
          strict: true

  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: avto-dev/markdown-lint@v1
        with:
          args: /github/workspace

  javadoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - run: mvn -B -ntp dependency:go-offline
      - run: mvn -B -ntp javadoc:javadoc-no-fork -Ddoclint=all

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - run: mvn -B -ntp dependency:go-offline
      - run: mvn -B -ntp checkstyle:check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven
          server-id: sonatype-nexus
          server-username: SERVER_USERNAME
          server-password: SERVER_PASSWORD
      - run: mvn -B -ntp dependency:go-offline
      - run: mvn -B -ntp verify -Dcheckstyle.skip -Dmaven.test.redirectTestOutputToFile=false
        if: ${{ github.ref != 'refs/heads/main' }}
      - run: mvn -B -ntp deploy -Dcheckstyle.skip -Dmaven.test.redirectTestOutputToFile=false
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          SERVER_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
